### ISSUE TITLE
Article about Image control lacks information about AutomationId

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/xamarin-docs.pl-pl#3]
Image control has property "AutomationId". There is no information about it in this article.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Obrazy w interfejsie Xamarin.Forms - Xamarin](https://docs.microsoft.com/pl-pl/xamarin/xamarin-forms/user-interface/images?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs.pl-PL/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Mikilll94 

`AutomationId` is present on most controls, and is covered [here](https://docs.microsoft.com/xamarin/xamarin-forms/deploy-test/uitest-and-test-cloud).

**Comment by CeciAc** [comment]
Hello, @Mikilll94
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. 
Did the response above solve the issue?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Mikilll94 
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @Mikilll94 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
